version: '3.6'

service:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid &&
      bundle check || bundle install &&
      yarn install &&
      bundle exec rails s -p 3000 -b '0.0.0.0'"
